/* DO NOT EDIT THIS FILE - it is machine generated */
#include <opencv2/core.hpp>
#include <opencv2/opencv.hpp>
#include "jni.h"
/* Header for class com_cs_cs_ImgCs */

#ifndef _Included_com_cs_cs_ImgCs
#define _Included_com_cs_cs_ImgCs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cs_cs_ImgCs
 * Method:    csencryp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cs_cs_ImgCs_csencryp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cs_cs_ImgCs
 * Method:    csdecryp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cs_cs_ImgCs_csdecryp
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
